# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis
  labels:
    app: sentiment-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
      - name: backend
        image: sentiment-analysis-backend
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
      - name: frontend
        image: sentiment-analysis-frontend
        ports:
        - containerPort: 8501
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: BACKEND_SERVICE
          value: "http://backend:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
spec:
  selector:
    app: sentiment-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer